let adminProfiles=[];
const safeText=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function adminMessage(text){$('admin-message').textContent=text;$('admin-message').hidden=!text}
async function loadProfiles(){if(!currentUser||currentUser.role!=='admin')return;try{adminProfiles=(await api('/api/admin/accounts')).accounts;renderProfiles();adminMessage('')}catch(e){adminMessage(e.message)}}
function renderProfiles(){const query=$('admin-search').value.trim().toLowerCase(),status=$('admin-status').value,roleFilter=$('admin-role').value;const list=adminProfiles.filter(p=>(status==='all'||p.status===status)&&(roleFilter==='all'||p.role===roleFilter)&&`${p.name} ${p.id} ${p.mobile}`.toLowerCase().includes(query));$('admin-stats').innerHTML=[['Pending review',adminProfiles.filter(p=>p.status==='pending').length],['Approved employees',adminProfiles.filter(p=>p.status==='approved'&&p.role==='employee').length],['Approved drivers',adminProfiles.filter(p=>p.status==='approved'&&p.role==='driver').length]].map(([label,count])=>`<div><span>${label}</span><strong>${count}</strong></div>`).join('');$('admin-profiles').innerHTML=list.length?list.map(p=>`<article class="admin-profile"><div class="admin-person"><span class="person-avatar">${safeText(p.name[0])}</span><div><h3>${safeText(p.name)}</h3><p>${safeText(p.id)} / ${p.role}</p></div></div><div class="admin-contact"><strong>${p.mobile?safeText(p.mobile):'No mobile provided'}</strong><p>${p.role==='employee'?safeText(STOPS[p.stop]?.name||'Pickup not set'):'Bus 02 driver profile'}</p></div><span class="approval-badge ${p.status}">${p.status}</span><button class="secondary review-profile" data-id="${safeText(p.id)}">Review / Edit</button></article>`).join(''):'<div class="admin-empty">No profiles match these filters.</div>';document.querySelectorAll('.review-profile').forEach(button=>button.onclick=()=>editProfile(button.dataset.id))}
function editProfile(id){const p=adminProfiles.find(profile=>profile.id===id);if(!p)return;$('edit-id').value=p.id;$('edit-identity').textContent=p.id+' / '+p.role+' (role is fixed)';$('edit-name').value=p.name;$('edit-mobile').value=p.mobile;$('edit-mobile').required=p.role==='driver';$('edit-pickup').hidden=p.role!=='employee';$('edit-stop').disabled=p.role!=='employee';$('edit-stop').value=p.stop??0;$('edit-status').value=p.status;$('edit-note').value=p.review_note;$('edit-error').hidden=true;$('profile-dialog').showModal()}
$('edit-stop').innerHTML=STOPS.map((s,i)=>`<option value="${i}">${s.name} / ${s.pickup} AM</option>`).join('');
$('profile-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type="submit"]');button.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if('stop' in data)data.stop=Number(data.stop);await api('/api/admin/update',data);$('profile-dialog').close();await loadProfiles();adminMessage('Profile saved. Service access now follows the selected approval status.')}catch(error){$('edit-error').textContent=error.message;$('edit-error').hidden=false}finally{button.disabled=false}};
$('close-profile').onclick=()=>$('profile-dialog').close();$('admin-refresh').onclick=loadProfiles;$('admin-search').oninput=renderProfiles;$('admin-role').onchange=renderProfiles;$('admin-status').onchange=renderProfiles;
setInterval(()=>{if(currentUser?.role==='admin'&&!$('profile-dialog').open)loadProfiles()},10000);
