'use strict';
const $=id=>document.getElementById(id);
const ROUTE=window.BUS_ROUTE;
const STOPS=ROUTE.stops;
const displayTime=value=>value+' AM';
const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};

let userPreferences={default_map:'auto',follow_bus:true,confirm_stop:true};
let serviceSettings={gps_stale_seconds:20,waiting_expiry_seconds:120,helpdesk:''};
let selectedStop=0;
let role='employee',state=null,connected=false,polling=false,mutating=false,watchId=null,latestFix=null,sending=false,nextRefresh=Date.now()+5000,receiptTime=0,serverAge=0;
let map=null,busMarker=null,accuracyCircle=null,following=true,stopMarkers=[],mapMode='route',mapChosen=false;
const WEAK_GPS_ACCURACY_METERS=100;
function routeStops(){return state?.stops||STOPS}
function routeStopIndex(stop=selectedStop){return state?.direction==='return'?STOPS.length-1-stop:stop}
function setScheduledDirection(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:ROUTE.timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(part=>[part.type,part.value]));$('trip-direction').value=parts.hour+':'+parts.minute>=ROUTE.returnDeparture?'return':'morning'}

async function api(path,data){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),4500);try{const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},credentials:'same-origin',body:data?JSON.stringify(data):undefined,cache:'no-store',signal:controller.signal});let result;try{result=await response.json()}catch{throw Error('Tracking server is not available. Run py server.py and open http://localhost:8000.')}if(!response.ok){if(response.status===403&&result.user&&result.user.status!=='approved')applyAccount(result.user);if(response.status===401&&currentUser)showLogin();throw Error(result.error||'Could not save the update.')}return result}finally{clearTimeout(timeout)}}
function notify(text){$('message').textContent=text;$('message').hidden=!text}
function setState(s){processPickupAlerts(s.pickup_alerts||[]);if(s.service)applyServiceSettings(s.service);if(s.driver){const contact=$('employee-driver-contact');contact.querySelector('strong').textContent=s.driver.name;const link=contact.querySelector('a');link.textContent='Call '+s.driver.mobile;link.href='tel:'+s.driver.mobile}if(s.profile&&currentUser&&s.profile.id===currentUser.id){currentUser=Object.freeze({...s.profile});$('profile-name').textContent=currentUser.name;$('profile-mobile').textContent='Mobile: '+currentUser.mobile;$('profile-badge').textContent=currentUser.name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();selectedStop=currentUser.stop??0;if($('stop-editor').hidden)$('stop-select').value=selectedStop}state=s;connected=true;receiptTime=Date.now();serverAge=s.location?Math.max(0,s.server_time-s.location.timestamp):0;if(!mapChosen&&s.active&&s.location&&serverAge<serviceSettings.gps_stale_seconds*1000&&Number.isFinite(s.location.lat)&&Number.isFinite(s.location.lng)&&mapMode!=='street')selectMap('street');render()}
async function refresh(){if(!currentUser||currentUser.status!=='approved'||role==='admin'||polling)return;polling=true;const identity=currentUser.id;nextRefresh=Date.now()+5000;try{if(role==='employee'&&state?.waiting!==null&&state?.waiting!==undefined)await api('/api/waiting',{waiting:true,heartbeat:true});const data=await api('/api/state');if(currentUser?.id===identity)setState(data)}catch(e){connected=false;notify(e.name==='AbortError'?'Connection timed out. Retrying every 5 seconds.':e.message);render()}finally{polling=false}}
async function act(action,extra={}){if(!currentUser||mutating)return false;const required=action==='waiting'?'employee':'driver';if(currentUser.role!==required){notify('This action is not available to your account.');return false}mutating=true;render();try{await api('/api/'+action,extra);setState(await api('/api/state'));notify('');return true}catch(e){notify(e.message);return false}finally{mutating=false;render()}}
$('stop-select').innerHTML=STOPS.map((s,i)=>`<option value="${i}">${i+1}. ${s.name} · ${displayTime(s.pickup)}</option>`).join('');$('stop-select').value=selectedStop;
$('waiting-button').onclick=()=>act('waiting',{waiting:state?.waiting!==routeStopIndex()});
$('reached-button').onclick=async()=>{if(userPreferences.confirm_stop&&!window.confirm('Confirm this pickup is complete and advance to the next stop?'))return;if(await act('reached')){if(!state.active)clearGPS();notify('Stop completed. The next pickup and waiting count have been updated.')}};
function clearGPS(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;latestFix=null;render()}
async function sendFix(){if(!currentUser||role!=='driver'||sending||watchId===null||!latestFix||!state?.active)return;sending=true;try{await api('/api/location',latestFix);notify('');await refresh()}catch(e){notify(e.name==='AbortError'?'GPS upload timed out. Retrying.':e.message)}finally{sending=false}}
$('gps-button').onclick=async()=>{if(watchId!==null){if(await act('stop'))clearGPS();return}if(!window.isSecureContext){notify('Phone GPS requires an HTTPS address. Localhost works on this computer.');return}if(!navigator.geolocation){notify('This browser does not provide GPS location.');return}if(!await act('start',{direction:$('trip-direction').value}))return;watchId=navigator.geolocation.watchPosition(p=>{latestFix={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp};sendFix()},e=>{latestFix=null;notify(e.code===1?'Location permission denied. Allow precise location access, then start sharing again.':'GPS is unavailable. Keep the page open and the phone awake; old positions will be marked stale.');if(e.code===1){clearGPS();act('stop')}},{enableHighAccuracy:true,maximumAge:0,timeout:30000});render()};
function locationAge(){return state?.location?serverAge+(Date.now()-receiptTime):Infinity}
function renderLocation(){const fix=state?.location,age=locationAge(),fresh=connected&&state?.active&&age<serviceSettings.gps_stale_seconds*1000,weak=Number.isFinite(fix?.accuracy)&&fix.accuracy>WEAK_GPS_ACCURACY_METERS;let label=!connected?'Connection lost · reconnecting':!state?.active?(state?.next_stop>=STOPS.length?'Trip completed':'Bus location sharing is off'):!fix?'Waiting for driver GPS':age>=serviceSettings.gps_stale_seconds*1000?'Location is out of date':weak?'GPS accuracy is weak · '+Math.round(fix.accuracy)+'m radius':'Bus location is live';$('location-status').textContent=label;$('location-age').textContent=fix?`Last GPS update ${Math.floor(age/1000)}s ago${Number.isFinite(fix.accuracy)?' · Device accuracy ±'+Math.round(fix.accuracy)+'m':''}`:'A bus marker appears when the driver shares a location.';$('signal').className='signal '+(fresh&&!weak?'live':fresh&&weak?'weak':fix?'stale':'');if(busMarker){busMarker.getElement()?.classList.toggle('old',!fresh);busMarker.getElement()?.classList.toggle('weak',fresh&&weak)}if(accuracyCircle)accuracyCircle.setStyle({color:fresh&&!weak?'#3183a5':'#89968d',fillColor:fresh&&!weak?'#48a6c7':'#9aa69c'});$('countdown').textContent=Math.max(1,Math.ceil((nextRefresh-Date.now())/1000))+'s';$('driver-freshness').textContent=!connected?'Offline · waiting count may be out of date':weak?'Weak GPS accuracy. Move outdoors for a clearer signal.':'Live GPS · updates every 5 seconds'}
function render(){if(!currentUser||currentUser.status!=='approved'||role==='admin')return;if(!state){$('waiting-button').disabled=true;$('gps-button').disabled=true;$('reached-button').disabled=true;return}const stops=routeStops(),selectedRouteStop=routeStopIndex(),mine=state.waiting===selectedRouteStop,complete=state.next_stop>=stops.length,returning=state.direction==='return';$('route-direction-label').textContent=returning?'UACPL - Auric Plant → UACPL - B-34':'UACPL - B-34 → UACPL - Auric Plant';$('waiting-button').disabled=mutating||!connected||complete||selectedRouteStop<state.next_stop;$('waiting-button').textContent=mine?'✓ You’re waiting · Tap to cancel':'I’m waiting at my stop';$('waiting-button').classList.toggle('waiting',mine);$('waiting-note').textContent=mine?'Your driver can now see you in the waiting count.':'Tap when you arrive. Your driver will see your count.';$('pickup-title').textContent=STOPS[selectedStop].name;$('pickup-time').textContent=returning?'Return route · no stop ETA available':'Revised pickup · '+displayTime(STOPS[selectedStop].pickup);$('pickup-detail').textContent=complete?'Trip completed':selectedRouteStop<state.next_stop?'Your pickup stop has been completed':selectedRouteStop===state.next_stop?'You’re at the next stop':`${selectedRouteStop-state.next_stop} stop${selectedRouteStop-state.next_stop===1?'':'s'} before yours`;$('next-name').textContent=complete?'All stops completed':stops[state.next_stop].name;$('next-time').textContent=complete?(returning?'Return route completed':'Morning route completed'):returning?'Live location · stop ETA unavailable':'Revised pickup · '+displayTime(stops[state.next_stop].pickup);$('waiting-count').textContent=complete?'0':state.counts[state.next_stop];$('gps-button').textContent=watchId!==null?'Stop sharing bus location':'Start sharing bus location';$('gps-button').disabled=mutating||!connected;$('reached-button').disabled=mutating||!connected||!state.active||complete;$('gps-note').textContent='Enable precise location, disable battery saver, and keep the phone outdoors with a clear sky view for the best GPS fix.';$('stop-list').innerHTML=stops.map((s,i)=>`<li class="${i<state.next_stop?'passed':i===state.next_stop?'next':''}"><div class="stop-heading"><span>${i+1}. ${s.name}</span><time>${returning?(i===0?'5:40 PM':'No ETA'):s.pickup+' AM'}</time></div><small>${returning&&i===0&&state.next_stop>0?'Departed · 5:40 PM':i<state.next_stop?'Completed':i===state.next_stop?'Next stop':i===selectedRouteStop&&role==='employee'?'Your stop':'Upcoming'}${role==='driver'?` · ${state.counts[i]} waiting`:''}</small></li>`).join('');$('schedule-label').textContent=returning?'Return · stop ETAs unavailable':'Revised pickup · AM';$('schedule-note').textContent=returning?'5:40 PM departure from UACPL - Auric Plant · Stops shown in reverse morning order':'07:50–08:50 AM · IST · Scheduled times, not live ETAs';renderLocation();drawSchematic();updateMap()}
function schematicPoint(index){const columns=innerWidth<680?2:4,rows=Math.ceil(STOPS.length/columns);const row=Math.floor(index/columns),column=index%columns;return {x:columns===2?22+(row%2?1-column:column)*56:12.5+(row%2?3-column:column)*25,y:12+row*(76/(rows-1))}}
function drawSchematic(){if(mapMode!=='route')return;const svg=$('fallback')?.querySelector('svg');if(!svg)return;const stops=routeStops(),returning=state?.direction==='return',svgLabel=returning?'Return route · stops in reverse morning order · no ETA':'All 16 named morning pickup stops with revised times';svg.setAttribute('aria-label',svgLabel);const mobile=innerWidth<680,width=mobile?700:1200,height=mobile?1750:850;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('preserveAspectRatio','xMidYMid meet');const points=stops.map((_,i)=>schematicPoint(i));svg.innerHTML=`<rect width="${width}" height="${height}" rx="16" fill="#f6f8f2"/><path d="${points.map((p,i)=>(i?'L':'M')+p.x*width/100+' '+p.y*height/100).join(' ')}" fill="none" stroke="#cbd8c0" stroke-width="7" stroke-linejoin="round"/>${points.map((p,i)=>{const next=state?.next_stop===i,mine=role==='employee'&&routeStopIndex()===i,passed=state&&i<state.next_stop,time=returning?(i===0?'5:40 PM':'ETA unavailable'):stops[i].pickup+' AM';return `<g transform="translate(${p.x*width/100} ${p.y*height/100})"><rect x="-135" y="-44" width="270" height="115" rx="15" fill="${next?'#224e3b':mine?'#e7f0d8':'white'}" stroke="${next?'#224e3b':mine?'#71934e':'#dce4d5'}" stroke-width="2"/><circle cx="-108" cy="-17" r="15" fill="${next?'#d6ec9e':'#edf2e5'}"/><text x="-108" y="-11" text-anchor="middle" font-family="sans-serif" font-size="17" font-weight="700" fill="#2c5035">${i+1}</text><text x="-82" y="-10" font-family="sans-serif" font-size="17" font-weight="600" fill="${next?'#ecf6df':'#63814b'}">${time}</text><text x="-116" y="23" font-family="sans-serif" font-size="${mobile?21:19}" font-weight="700" fill="${next?'white':'#294638'}">${stops[i].name}</text><text x="-116" y="51" font-family="sans-serif" font-size="16" fill="${next?'#d7ebad':'#748667'}">${returning&&i===0&&state?.next_stop>0?'DEPARTED':passed?'Completed':next?'NEXT STOP':mine?'YOUR STOP':'Stop '+(i+1)}</text></g>`}).join('')}`}
function updateMap(){const fix=state?.location;if(mapMode==='street'&&map){if(fix&&Number.isFinite(fix.lat)&&Number.isFinite(fix.lng)){if(!busMarker){busMarker=L.marker([fix.lat,fix.lng],{icon:L.divIcon({className:'bus-marker',html:'BUS<span>02</span>',iconSize:[60,44],iconAnchor:[30,22]}),zIndexOffset:1000}).addTo(map).bindTooltip('Bus 02 / MH 20 GZ 7053')}else busMarker.setLatLng([fix.lat,fix.lng]);if(Number.isFinite(fix.accuracy)){const radius=Math.max(0,fix.accuracy);if(!accuracyCircle)accuracyCircle=L.circle([fix.lat,fix.lng],{radius,color:'#3183a5',weight:1,fillColor:'#48a6c7',fillOpacity:.16,interactive:false}).addTo(map);else accuracyCircle.setLatLng([fix.lat,fix.lng]).setRadius(radius)}if(following)map.setView([fix.lat,fix.lng],Math.max(map.getZoom(),15),{animate:true})}else{if(busMarker){map.removeLayer(busMarker);busMarker=null}if(accuracyCircle){map.removeLayer(accuracyCircle);accuracyCircle=null}}renderLocation()}if($('fallback-bus'))$('fallback-bus').hidden=true;stopMarkers.forEach(({marker,index})=>marker.setStyle({fillColor:index<(state?.next_stop??0)?'#adb6a0':index===(state?.next_stop??0)?'#365e43':'white'}))}
function initMap(){if(mapMode!=='street'){drawSchematic();return}if(map||!window.L)return;$('map').innerHTML='';map=L.map('map',{zoomControl:false}).setView([19.875,75.350],12);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map).on('tileerror',()=>$('map-note').textContent='Street tiles unavailable. Try Route & stops.');stopMarkers=routeStops().flatMap((s,index)=>Number.isFinite(s.lat)&&Number.isFinite(s.lng)?[{index,marker:L.circleMarker([s.lat,s.lng],{radius:7,color:'#52744c',weight:3,fillColor:'white',fillOpacity:1}).addTo(map).bindTooltip(s.name+(state?.direction==='return'?'':' / '+displayTime(s.pickup)))}]:[]);map.on('dragstart',()=>following=false);if(state)updateMap()}
function selectMap(mode){mapMode=mode;$('route-map-button').classList.toggle('active',mode==='route');$('street-map-button').classList.toggle('active',mode==='street');if(map){map.remove();map=null;busMarker=null;accuracyCircle=null;stopMarkers=[]}if(mode==='route'){$('map').innerHTML='<div id="fallback"><svg aria-label="All 16 named pickup stops with revised times"></svg></div>';$('map-note').textContent=state?.direction==='return'?'Return route · GPS is live; stop ETAs are unavailable':'Route diagram / 16 stops / Scheduled pickup times';drawSchematic()}else{$('map-note').textContent='Live GPS position; shaded circle shows device-reported accuracy. Stop pins/ETAs unavailable.';if(!window.L){$('map').innerHTML='<div class="map-unavailable">Street map is loading. Check your internet connection or use Route & stops.</div>'}else initMap()}$('recenter').hidden=mode==='route';updateMap()}
function mapFailed(){if(mapMode==='street')$('map-note').textContent='Street map unavailable. Use Route & stops.'}
$('route-map-button').onclick=()=>{mapChosen=true;selectMap('route')};$('street-map-button').onclick=()=>{mapChosen=true;selectMap('street')};$('recenter').onclick=()=>{following=true;updateMap()};
$('expand-map').onclick=()=>{const expanded=document.querySelector('.map-card').classList.toggle('expanded');$('expand-map').textContent=expanded?'Close expanded map':'Expand map';map?.invalidateSize();drawSchematic()};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.map-card').classList.remove('expanded');$('expand-map').textContent='Expand map';map?.invalidateSize()}});
window.addEventListener('resize',()=>drawSchematic());document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentUser)refresh()});
$('mode').textContent='LIVE GPS / 5 SECOND REFRESH';$('footer-mode').textContent='Your account. Your pickup. Your journey.';setScheduledDirection();
selectMap('route');setInterval(refresh,5000);setInterval(sendFix,5000);setInterval(()=>{if(currentUser&&currentUser.status==='approved'&&role!=='admin')renderLocation()},1000);
