let currentUser=null;
function authMessage(message){$('auth-message').textContent=message;$('auth-message').hidden=!message}
function showLogin(){$('pickup-alert').hidden=true;$('settings-dialog').close();$('password-form').reset();$('admin-main').hidden=true;$('approval-screen').hidden=true;$('profile-dialog').close();currentUser=null;state=null;connected=false;clearGPS();$('app-main').hidden=true;$('account-menu').hidden=true;$('auth-screen').hidden=false;$('login-form').hidden=false;$('register-form').hidden=true}
async function applyAccount(user){$('admin-main').hidden=true;$('approval-screen').hidden=true;currentUser=Object.freeze({...user});role=user.role;await loadUserSettings();if(user.status!=='approved'){showApproval(user);return}if(role==='admin'){$('auth-screen').hidden=true;$('app-main').hidden=true;$('account-menu').hidden=false;$('account-role').textContent='Admin account';$('admin-main').hidden=false;clearGPS();await loadProfiles();return}selectedStop=user.stop??0;$('auth-screen').hidden=true;$('app-main').hidden=false;$('account-menu').hidden=false;$('account-role').textContent=role==='driver'?'Driver account':'Employee account';$('employee-panel').hidden=role!=='employee';$('driver-panel').hidden=role!=='driver';$('profile-name').textContent=user.name;$('profile-id').textContent=role==='employee'?'Employee ID: '+user.id:'Driver ID: '+user.id;$('employee-driver-contact').hidden=role!=='employee';$('profile-mobile').hidden=role!=='driver';$('profile-mobile').textContent='Mobile: '+user.mobile;$('profile-badge').textContent=user.name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();$('stop-select').value=selectedStop;$('stop-editor').hidden=true;$('heading').textContent=role==='driver'?'Your next stop. Everyone counted.':'Your bus. One glance away.';$('intro-text').textContent=role==='driver'?'Share your bus location and see who is waiting at the next stop.':'Your saved pickup, your bus and your driver, all in one place.';drawSchematic();map?.invalidateSize();render();await refresh()}
$('register-stop').innerHTML=STOPS.map((s,i)=>`<option value="${i}">${s.name} - ${s.pickup} AM</option>`).join('');
$('show-register').onclick=()=>{$('login-form').hidden=true;$('register-form').hidden=false;authMessage('')};
$('show-login').onclick=()=>{$('login-form').hidden=false;$('register-form').hidden=true;authMessage('')};
async function submitAuth(form,path){const button=form.querySelector('[type="submit"]');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));if('stop' in data)data.stop=Number(data.stop);const result=await api(path,data);form.reset();$('register-role').onchange();authMessage('');await applyAccount(result.user)}catch(e){authMessage(e.message)}finally{button.disabled=false}}
$('login-form').onsubmit=e=>{e.preventDefault();submitAuth(e.target,'/api/login')};
$('register-form').onsubmit=e=>{e.preventDefault();submitAuth(e.target,'/api/register')};
$('logout-button').onclick=async()=>{try{await api('/api/logout',{});showLogin()}catch(e){notify('Could not sign out. Check your connection and try again.')}};
$('change-stop').onclick=()=>{$('stop-select').value=selectedStop;$('stop-editor').hidden=false};
$('cancel-stop').onclick=()=>{$('stop-editor').hidden=true;$('stop-select').value=selectedStop};
$('save-stop').onclick=async()=>{const button=$('save-stop');button.disabled=true;try{const result=await api('/api/profile',{stop:Number($('stop-select').value)});await applyAccount(result.user);notify('Your pickup is saved for future logins. Mark yourself waiting again if you are at the new stop.')}catch(e){notify(e.message)}finally{button.disabled=false}};
async function bootstrapAuth(){if(location.protocol==='file:'){authMessage('Start py server.py and open http://localhost:8000 to sign in. Accounts need the server.');return}try{const result=await api('/api/me');await applyAccount(result.user)}catch(e){showLogin();if(!e.message.includes('sign in'))authMessage(e.message)}}
function showApproval(user){$('settings-dialog').close();clearGPS();state=null;currentUser=Object.freeze({...user});$('app-main').hidden=true;$('admin-main').hidden=true;$('auth-screen').hidden=true;$('account-menu').hidden=false;$('account-role').textContent=user.role+' / '+user.status;$('approval-screen').hidden=false;$('approval-title').textContent={pending:'Waiting for approval',rejected:'Profile not approved',suspended:'Service access suspended'}[user.status]||'Approval required';$('approval-description').textContent='Your '+user.role+' profile must be approved by a transport admin.';$('approval-profile').textContent=user.name+' / '+user.id;$('approval-note').textContent=user.review_note||'Your profile is saved. Check back here for the admin decision.'}
$('register-role').onchange=()=>{const driver=$('register-role').value==='driver';$('register-pickup').hidden=driver;$('register-stop').disabled=driver;$('register-mobile').required=driver};
$('check-approval').onclick=async()=>{try{await applyAccount((await api('/api/me')).user)}catch(e){$('approval-note').textContent=e.message}};
setInterval(()=>{if(currentUser&&currentUser.status!=='approved')$('check-approval').onclick()},5000);
bootstrapAuth();

